/**
 * EduPortal feature page definitions — used by scripts/generate-feature-pages.mjs
 */
export const FEATURES = [
  {
    slug: 'student-information-system',
    title: 'Student Information System',
    metaTitle: 'Student Information System for Schools in Pakistan | EduPortal ERP',
    metaDescription: 'EduPortal student information system (SIS) centralizes admissions, profiles, guardians, documents & class history. Trusted school ERP Pakistan for 500+ campuses.',
    keywords: 'student information system Pakistan, school SIS software, student records ERP, school management software Pakistan',
    icon: 'users',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal student information system dashboard',
    tagline: 'One digital profile for every student — from admission to graduation.',
    pain: 'scattered paper files, duplicate Excel sheets, and lost admission documents',
    outcomes: 'searchable profiles, complete guardian records, and audit-ready archives',
    modules: ['digital admission forms', 'guardian & emergency contacts', 'medical & allergy notes', 'document uploads', 'class & section history', 'student ID linking', 'promotion & transfer logs', 'custom profile fields', 'bulk import/export', 'role-based access'],
    related: ['online-admissions', 'attendance-management', 'examination-management'],
  },
  {
    slug: 'online-admissions',
    title: 'Online Admissions',
    metaTitle: 'Online School Admissions Software Pakistan | EduPortal ERP',
    metaDescription: 'Digitize school admissions with EduPortal — online forms, document upload, merit lists, fee linking & enrollment workflows. School ERP Pakistan built for admission season.',
    keywords: 'online school admissions Pakistan, admission management software, school enrollment ERP',
    icon: 'user-plus',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal online admissions workflow',
    tagline: 'Capture inquiries, process applications, and enroll students without paper chaos.',
    pain: 'long admission queues, manual form sorting, and enrollment errors every April',
    outcomes: 'faster enrollment, organized merit lists, and linked fee accounts from day one',
    modules: ['online application forms', 'document verification', 'merit list generation', 'interview scheduling', 'admission fee collection', 'seat capacity tracking', 'waitlist management', 'SMS status updates', 'enrollment to SIS sync', 'multi-campus intake'],
    related: ['student-information-system', 'fee-management', 'whatsapp-communication'],
  },
  {
    slug: 'attendance-management',
    title: 'Attendance Management',
    metaTitle: 'Digital Attendance — Face Recognition & QR Code | EduPortal Pakistan',
    metaDescription: 'AI face recognition attendance (1-sec scan), QR card scanning, manual & app marking. Auto-sync with EduPortal school ERP. Used by big & small institutes across Pakistan.',
    keywords: 'digital attendance system Pakistan, face recognition attendance school, QR code attendance, school attendance software Pakistan, AI attendance machine',
    icon: 'scan-face',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal digital attendance with face recognition and QR scanning',
    tagline: 'Manual, mobile app, AI face recognition, or QR card scanning — attendance that fits every campus and budget.',
    pain: 'late registers, manual machine enrollment, and no visibility into chronic absenteeism',
    outcomes: '1-second digital check-in, auto-synced records, and instant parent alerts',
    modules: [
      'AI face recognition machine (1-sec scan)',
      'auto-sync from software photos — no manual machine registration',
      'student & staff face attendance',
      'QR code scanning on ID cards',
      'class-wise manual marking',
      'teacher mobile app attendance',
      'biometric device integration',
      'instant parent SMS/app alerts',
      'late arrival & leave tracking',
      'daily & monthly attendance reports',
      'board exam attendance sheets',
      'real-time owner dashboards',
    ],
    related: ['id-cards-generation', 'parent-mobile-app', 'teacher-mobile-app'],
    demoVideo: 'QKHYk0vdkjY',
  },
  {
    slug: 'fee-management',
    title: 'Fee Management',
    metaTitle: 'School Fee Management Software Pakistan | EduPortal ERP',
    metaDescription: 'Automate fee structures, vouchers, collections, concessions & defaulter tracking. EduPortal fee management module for Pakistani schools — reduce front-desk workload.',
    keywords: 'school fee management software Pakistan, fee collection ERP, automated fee vouchers',
    icon: 'wallet',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal fee management and voucher system',
    tagline: 'Define fee heads, generate vouchers in bulk, and track every rupee collected.',
    pain: 'manual voucher printing, missed concessions, and endless defaulter follow-ups',
    outcomes: 'accurate billing, faster collections, and clear aging reports for owners',
    modules: ['fee structure by class', 'installment plans', 'sibling discounts', 'scholarship rules', 'bulk voucher generation', 'partial payments', 'fine & late fees', 'defaulter reports', 'receipt printing', 'fee ledger sync'],
    related: ['accounting-management', 'whatsapp-communication', 'parent-mobile-app'],
  },
  {
    slug: 'examination-management',
    title: 'Examination Management',
    metaTitle: 'School Exam & Result Management Software | EduPortal Pakistan',
    metaDescription: 'Manage exams, marks entry, grading scales, report cards & result publishing with EduPortal. Complete examination module for school ERP Pakistan.',
    keywords: 'school exam management software, result management ERP Pakistan, report card software',
    icon: 'award',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal examination and results module',
    tagline: 'Configure exams, enter marks securely, and publish results parents trust.',
    pain: 'marksheet errors, delayed result days, and retyping grades for report cards',
    outcomes: 'accurate results, branded report cards, and secure parent portal publishing',
    modules: ['exam type setup', 'subject-wise marks', 'grading scales', 'position holders', 'report card templates', 'result analytics', 're-evaluation workflow', 'parent portal publish', 'PDF bulk export', 'board format compliance'],
    related: ['exam-datasheets', 'student-information-system', 'parent-mobile-app'],
  },
  {
    slug: 'timetable-management',
    title: 'Timetable Management',
    metaTitle: 'School Timetable Software Pakistan | EduPortal ERP',
    metaDescription: 'Build clash-free timetables for teachers, rooms & sections. EduPortal timetable module keeps staff and students aligned across your school ERP Pakistan.',
    keywords: 'school timetable software Pakistan, academic scheduling ERP, class timetable generator',
    icon: 'calendar-days',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal timetable and scheduling',
    tagline: 'Drag-and-drop schedules that avoid conflicts and sync to mobile apps.',
    pain: 'double-booked teachers, last-minute sticky notes, and confused substitute plans',
    outcomes: 'conflict-free timetables, live updates, and coordinated substitutions',
    modules: ['period configuration', 'room allocation', 'teacher load balancing', 'section timetables', 'substitution tracking', 'mobile timetable view', 'PDF export', 'multi-shift support', 'lab scheduling', 'exam week layouts'],
    related: ['teacher-mobile-app', 'lesson-plans-syllabus', 'attendance-management'],
  },
  {
    slug: 'lesson-plans-syllabus',
    title: 'Lesson Plans & Syllabus Tracking',
    metaTitle: 'Lesson Plan & Syllabus Tracking for Schools | EduPortal',
    metaDescription: 'Teachers log daily lesson plans aligned to syllabus coverage. Academic coordinators monitor progress before board exams with EduPortal school ERP Pakistan.',
    keywords: 'lesson plan software schools, syllabus tracking ERP, academic planning Pakistan',
    icon: 'book-open',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal lesson plan and syllabus tracking',
    tagline: 'Ensure curriculum completion with visible lesson plans and coverage dashboards.',
    pain: 'unknown syllabus gaps discovered weeks before board exams',
    outcomes: 'coordinated teaching, visible progress, and inspection-ready documentation',
    modules: ['daily lesson logs', 'syllabus mapping', 'topic completion %', 'coordinator review', 'resource attachments', 'weekly plans', 'subject-wise targets', 'inspection reports', 'teacher accountability', 'multi-grade templates'],
    related: ['lms-management', 'timetable-management', 'teacher-mobile-app'],
  },
  {
    slug: 'lms-management',
    title: 'Learning Management System (LMS)',
    metaTitle: 'School LMS Software Pakistan | EduPortal Learning Module',
    metaDescription: 'EduPortal LMS delivers assignments, study material, quizzes & progress tracking inside your school ERP. Engage students and parents with digital learning in Pakistan.',
    keywords: 'school LMS Pakistan, learning management system schools, digital classroom ERP',
    icon: 'graduation-cap',
    heroImage: 'assets/parent-app.jpg',
    heroAlt: 'EduPortal LMS and digital learning',
    tagline: 'Share materials, assign homework, and track learning progress digitally.',
    pain: 'WhatsApp homework chains, lost worksheets, and no record of submissions',
    outcomes: 'organized assignments, submission tracking, and parent visibility into homework',
    modules: ['study material upload', 'video links', 'assignment creation', 'submission tracking', 'online quizzes', 'grade sync', 'parent notifications', 'subject folders', 'teacher comments', 'progress dashboards'],
    related: ['lesson-plans-syllabus', 'parent-mobile-app', 'teacher-mobile-app'],
  },
  {
    slug: 'library-management',
    title: 'Library Management',
    metaTitle: 'School Library Management Software | EduPortal ERP Pakistan',
    metaDescription: 'Catalog books, manage issuance, returns, fines & overdue alerts with EduPortal library module. Complete school ERP Pakistan for modern libraries.',
    keywords: 'school library software Pakistan, book issuance system, library ERP',
    icon: 'library',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal library management system',
    tagline: 'Digital catalog, issuance tracking, and overdue reminders without manual registers.',
    pain: 'lost books, handwritten ledgers, and uncollected fines',
    outcomes: 'organized catalog, automated due dates, and clear accountability per borrower',
    modules: ['ISBN catalog', 'book categories', 'student issuance', 'staff issuance', 'due date tracking', 'fine calculation', 'overdue SMS', 'stock reports', 'barcode support', 'popular titles analytics'],
    related: ['inventory-management', 'student-information-system', 'sms-messaging'],
  },
  {
    slug: 'transport-management',
    title: 'Transport Management',
    metaTitle: 'School Transport Management Software Pakistan | EduPortal',
    metaDescription: 'Manage routes, vehicles, drivers & transport fees with EduPortal. Parents see pickup points in the app — safer commutes for school ERP Pakistan users.',
    keywords: 'school transport software Pakistan, route management ERP, student transport tracking',
    icon: 'bus',
    heroImage: 'assets/parent-app.jpg',
    heroAlt: 'EduPortal transport and route management',
    tagline: 'Assign routes, link transport fees, and keep parents informed about pickups.',
    pain: 'route confusion, manual transport fee billing, and safety communication gaps',
    outcomes: 'clear route assignments, integrated billing, and parent app visibility',
    modules: ['route planning', 'vehicle registry', 'driver profiles', 'student-route mapping', 'pickup points', 'transport fee heads', 'capacity tracking', 'parent app view', 'route change alerts', 'monthly route reports'],
    related: ['fee-management', 'parent-mobile-app', 'student-information-system'],
  },
  {
    slug: 'hostel-management',
    title: 'Hostel Management',
    metaTitle: 'School Hostel Management Software | EduPortal ERP Pakistan',
    metaDescription: 'Room allocation, boarding fees, hostel attendance & warden dashboards for residential schools. EduPortal hostel module in one school ERP Pakistan platform.',
    keywords: 'hostel management software schools, boarding school ERP Pakistan',
    icon: 'home',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal hostel management dashboard',
    tagline: 'Manage rooms, boarders, fees, and warden operations from one dashboard.',
    pain: 'manual room charts, missed hostel fees, and paper leave registers',
    outcomes: 'visible occupancy, linked hostel billing, and warden-friendly workflows',
    modules: ['room & bed allocation', 'hostel fee billing', 'boarder profiles', 'leave requests', 'visitor logs', 'discipline notes', 'mess fee linking', 'occupancy reports', 'warden mobile view', 'parent notifications'],
    related: ['fee-management', 'attendance-management', 'student-information-system'],
  },
  {
    slug: 'canteen-pos',
    title: 'Canteen & POS System',
    metaTitle: 'School Canteen POS Software | EduPortal ERP Pakistan',
    metaDescription: 'Fast canteen POS tied to student wallets or cash. Track daily sales, stock & revenue with EduPortal — school management software Pakistan.',
    keywords: 'school canteen POS, cafeteria management software schools',
    icon: 'shopping-cart',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal canteen point of sale',
    tagline: 'Sell meals quickly with POS linked to student accounts and daily revenue reports.',
    pain: 'cash handling errors, no sales visibility, and manual stock counts',
    outcomes: 'fast checkout, prepaid wallets, and daily canteen P&L clarity',
    modules: ['POS checkout', 'student wallet', 'menu management', 'daily sales report', 'stock consumption', 'cash vs wallet split', 'item popularity', 'staff canteen sales', 'receipt printing', 'inventory link'],
    related: ['inventory-management', 'fee-management', 'accounting-management'],
  },
  {
    slug: 'parent-mobile-app',
    title: 'Parent Mobile App',
    metaTitle: 'Parent Portal & Mobile App for Schools | EduPortal Pakistan',
    metaDescription: 'ParentsConnect app — view attendance, fees, results, homework & notices on mobile. Top parent portal for school ERP Pakistan with push notifications.',
    keywords: 'parent portal app Pakistan, school parent mobile app, ParentsConnect EduPortal',
    icon: 'smartphone',
    heroImage: 'assets/parent-app.jpg',
    heroAlt: 'EduPortal ParentsConnect mobile app',
    tagline: 'Give parents instant access to attendance, fees, results, and school notices.',
    pain: 'endless phone calls to the office for fee and result updates',
    outcomes: 'informed families, fewer front-desk calls, and stronger school trust',
    modules: ['attendance view', 'fee dues & receipts', 'exam results', 'homework notices', 'school calendar', 'push notifications', 'teacher messages', 'transport info', 'leave requests', 'multi-child support'],
    related: ['teacher-mobile-app', 'whatsapp-communication', 'fee-management'],
  },
  {
    slug: 'teacher-mobile-app',
    title: 'Teacher Mobile App',
    metaTitle: 'Teacher Mobile App for Schools | EduPortal ERP Pakistan',
    metaDescription: 'EduPortal teacher app — mark attendance, enter marks, share homework & view timetables from mobile. Essential school ERP Pakistan tool for classroom staff.',
    keywords: 'teacher mobile app schools Pakistan, teacher ERP app, classroom management app',
    icon: 'tablet-smartphone',
    heroImage: 'assets/parent-app.jpg',
    heroAlt: 'EduPortal teacher mobile application',
    tagline: 'Empower teachers to mark attendance, enter marks, and share updates on the go.',
    pain: 'teachers waiting for office computers to update records after class',
    outcomes: 'same-day data entry, mobile timetables, and faster academic workflows',
    modules: ['mobile attendance', 'marks entry', 'homework posting', 'timetable view', 'class lists', 'leave approval view', 'lesson plan logs', 'push alerts', 'offline queue', 'secure login'],
    related: ['parent-mobile-app', 'attendance-management', 'examination-management'],
  },
  {
    slug: 'sms-messaging',
    title: 'SMS Messaging',
    metaTitle: 'Bulk SMS for Schools Pakistan | EduPortal SIM Messaging',
    metaDescription: 'Send fee reminders, holidays, exam schedules & emergency alerts via school SIM integration. Reliable bulk SMS for school ERP Pakistan with delivery logs.',
    keywords: 'school bulk SMS Pakistan, SIM messaging schools, SMS fee reminders',
    icon: 'message-square',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal bulk SMS messaging',
    tagline: 'Reach thousands of parents in minutes with branded SMS from your SIM.',
    pain: 'manual texting, no delivery proof, and missed fee reminder campaigns',
    outcomes: 'logged bulk sends, targeted lists, and reliable parent reach',
    modules: ['SIM integration', 'bulk campaigns', 'fee reminders', 'holiday notices', 'exam alerts', 'class-wise filters', 'delivery logs', 'template library', 'scheduled sends', 'emergency broadcasts'],
    related: ['whatsapp-communication', 'fee-management', 'parent-mobile-app'],
  },
  {
    slug: 'whatsapp-communication',
    title: 'WhatsApp Communication',
    metaTitle: 'WhatsApp Messaging for Schools | EduPortal ERP Pakistan',
    metaDescription: 'Send fee dues, events & result alerts on WhatsApp where parents already chat. Template-based WhatsApp module for school management software Pakistan.',
    keywords: 'WhatsApp school messaging Pakistan, parent WhatsApp alerts ERP',
    icon: 'message-circle',
    heroImage: 'assets/parent-app.jpg',
    heroAlt: 'EduPortal WhatsApp school communication',
    tagline: 'Deliver notices on WhatsApp with templates for fees, events, and results.',
    pain: 'parents missing SMS but active on WhatsApp groups all day',
    outcomes: 'higher read rates, template consistency, and channel choice per campaign',
    modules: ['WhatsApp templates', 'fee due messages', 'event invitations', 'result announcements', 'class-wise sends', 'delivery status', 'media attachments', 'opt-in lists', 'campaign history', 'ERP data merge fields'],
    related: ['sms-messaging', 'parent-mobile-app', 'fee-management'],
  },
  {
    slug: 'id-cards-generation',
    title: 'ID Cards Generation',
    metaTitle: 'School ID Card Generator with Auto QR Code | EduPortal Pakistan',
    metaDescription: 'Design & batch-print student & staff ID cards with auto-generated QR codes for digital attendance. Cards sync from EduPortal SIS — no designer needed. School ERP Pakistan.',
    keywords: 'school ID card generator Pakistan, QR code ID cards schools, student ID card software, automatic ID card printing ERP',
    icon: 'id-card',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal ID card generation with QR codes for attendance',
    tagline: 'Auto-design and print QR-coded ID cards for students and staff — ready for digital attendance scanning.',
    pain: 'designer delays, manual QR creation, and cards disconnected from attendance',
    outcomes: 'same-day card printing, embedded QR codes, and seamless attendance check-in',
    modules: [
      'auto ID card design from templates',
      'student & staff card layouts',
      'QR code auto-printed on every card',
      'photos pulled from student/staff profiles',
      'school logo & branding',
      'batch PDF generation',
      'barcode support',
      'linked to QR attendance scanning',
      'reprint & replacement cards',
      'custom fields & class info on card',
    ],
    related: ['attendance-management', 'certificates-id-cards', 'student-information-system'],
  },
  {
    slug: 'certificates-id-cards',
    title: 'Certificates & ID Cards',
    metaTitle: 'School Certificates & Character Certificate Generator | EduPortal',
    metaDescription: 'Print leaving certificates, character certificates, achievement awards & more with your school branding. Batch generate from EduPortal school ERP Pakistan.',
    keywords: 'school certificate generator Pakistan, leaving certificate software, character certificate schools',
    icon: 'award',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal school certificate generator',
    tagline: 'Batch-generate leaving certificates, character certificates, and achievement awards with your branding.',
    pain: 'designer delays and manual mail-merge every graduation season',
    outcomes: 'same-day certificate printing, consistent branding, and linked student records',
    modules: ['leaving certificates', 'character certificates', 'achievement awards', 'principal signature block', 'batch PDF export', 'custom templates', 'student data merge', 'Urdu/English layouts', 'graduation season bulk print', 'archive & reprint'],
    related: ['id-cards-generation', 'student-information-system', 'examination-management'],
  },
  {
    slug: 'exam-datasheets',
    title: 'Exam Datasheets & Roll Slips',
    metaTitle: 'Exam Datasheets & Roll Number Slips | EduPortal ERP',
    metaDescription: 'Export exam datasheets, seating plans & roll number slips formatted for board exams. One-click exam coordination for school ERP Pakistan.',
    keywords: 'exam datasheet software schools, roll number slip generator Pakistan',
    icon: 'file-spreadsheet',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal exam datasheets and roll slips',
    tagline: 'Print accurate seating plans and roll slips before exam day in one click.',
    pain: 'last-minute seating mistakes and manual roll slip typing',
    outcomes: 'room-wise accuracy, board-ready formats, and coordinator peace of mind',
    modules: ['datasheet export', 'seating plans', 'roll number slips', 'room allocation', 'invigilator lists', 'board format presets', 'bulk PDF print', 'student photo sheets', 'subject-wise lists', 'exam day checklists'],
    related: ['examination-management', 'student-information-system', 'id-cards-generation'],
  },
  {
    slug: 'accounting-management',
    title: 'Accounting Management',
    metaTitle: 'School Accounting Software Pakistan | EduPortal Finance ERP',
    metaDescription: 'General ledger, chart of accounts & financial statements for schools. EduPortal accounting module — no separate software needed. School ERP Pakistan.',
    keywords: 'school accounting software Pakistan, school finance ERP, ledger management schools',
    icon: 'landmark',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal school accounting and finance',
    tagline: 'Run school accounts with ledger, statements, and auditor-ready reports.',
    pain: 'fee income in one tool and expenses in another with no single truth',
    outcomes: 'unified books, automated statements, and owner-ready financial clarity',
    modules: ['chart of accounts', 'journal entries', 'bank reconciliation', 'balance sheet', 'profit & loss', 'cash flow', 'fee-to-ledger sync', 'voucher printing', 'multi-year archives', 'auditor export'],
    related: ['fee-management', 'expenses-profit-loss', 'payroll-management'],
  },
  {
    slug: 'payroll-management',
    title: 'Payroll Management',
    metaTitle: 'School Payroll Software Pakistan | EduPortal Staff Salary ERP',
    metaDescription: 'Staff profiles, salary structures, deductions & monthly payroll with payslips. EduPortal payroll for school ERP Pakistan linked to attendance & leave.',
    keywords: 'school payroll software Pakistan, staff salary management ERP',
    icon: 'banknote',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal payroll and salary management',
    tagline: 'Process staff payroll accurately with attendance-linked deductions.',
    pain: 'manual payslip math and mismatched leave deductions every month',
    outcomes: 'automated payroll runs, payslip PDFs, and linked HR records',
    modules: ['salary structures', 'allowances', 'deductions', 'monthly payroll run', 'payslip PDF', 'bank advice', 'leave integration', 'increment history', 'tax fields', 'staff cost reports'],
    related: ['accounting-management', 'attendance-management', 'expenses-profit-loss'],
  },
  {
    slug: 'expenses-profit-loss',
    title: 'Expenses & Profit/Loss Tracking',
    metaTitle: 'School Expense & P&L Tracking | EduPortal ERP Pakistan',
    metaDescription: 'Record daily expenses by category and see real-time profit & loss vs fee income. School owners get clear dashboards with EduPortal school ERP Pakistan.',
    keywords: 'school expense tracking software, profit loss schools Pakistan',
    icon: 'trending-up',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal expense and profit loss tracking',
    tagline: 'See where money goes and how fee income compares to operating costs.',
    pain: 'owners discovering cash shortfalls weeks after expenses pile up',
    outcomes: 'category-wise spend visibility, monthly P&L, and smarter budget calls',
    modules: ['expense categories', 'daily entry', 'vendor tracking', 'utility bills', 'maintenance logs', 'P&L dashboard', 'month comparison', 'campus-wise split', 'approval workflow', 'export to accounts'],
    related: ['accounting-management', 'fee-management', 'inventory-management'],
  },
  {
    slug: 'inventory-management',
    title: 'Inventory Management',
    metaTitle: 'School Inventory & Stock Management | EduPortal ERP',
    metaDescription: 'Track uniforms, books, lab supplies & stationery with inward/outward logs and low-stock alerts. Inventory module for school management software Pakistan.',
    keywords: 'school inventory software Pakistan, stock management ERP schools',
    icon: 'package',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal inventory and stock management',
    tagline: 'Never run out of uniforms or lab supplies before the new session.',
    pain: 'surprise stockouts and no vendor purchase history',
    outcomes: 'stock visibility, reorder alerts, and cost control per category',
    modules: ['item catalog', 'inward/outward', 'low-stock alerts', 'vendor records', 'purchase history', 'issue to student', 'department issues', 'valuation reports', 'barcode optional', 'session-wise planning'],
    related: ['canteen-pos', 'library-management', 'accounting-management'],
  },
  {
    slug: 'multi-campus-management',
    title: 'Multi-Campus Management',
    metaTitle: 'Multi-Campus School ERP Pakistan | EduPortal',
    metaDescription: 'Operate multiple branches from one owner dashboard — consolidated reports, per-campus data & shared policies. Scale your school group with EduPortal ERP.',
    keywords: 'multi campus school ERP Pakistan, school franchise software',
    icon: 'building-2',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal multi-campus management',
    tagline: 'One platform for every branch with consolidated owner visibility.',
    pain: 'duplicate systems per campus and delayed group-level reporting',
    outcomes: 'central governance, branch autonomy, and unified analytics',
    modules: ['branch setup', 'consolidated dashboard', 'per-campus isolation', 'shared fee policies', 'group reports', 'cross-campus transfer', 'owner login', 'branch comparisons', 'central user admin', 'franchise billing'],
    related: ['accounting-management', 'student-information-system', 'customization-options'],
  },
  {
    slug: 'customer-support',
    title: 'Dedicated Customer Support',
    metaTitle: 'EduPortal School ERP Support & Training | Pakistan',
    metaDescription: 'Priority support, onboarding, training & fast resolution during fee and exam seasons. Dedicated customer success for EduPortal school ERP Pakistan clients.',
    keywords: 'EduPortal support, school ERP training Pakistan, ERP onboarding schools',
    icon: 'headphones',
    heroImage: 'assets/logo_icon.jpg',
    heroAlt: 'EduPortal dedicated customer support',
    tagline: 'Real humans who understand schools — setup, training, and year-round help.',
    pain: 'generic helpdesks that do not understand admission or exam urgency',
    outcomes: 'faster go-live, confident staff, and reliable help when it matters',
    modules: ['onboarding calls', 'data migration help', 'staff training', 'WhatsApp support', 'remote assistance', 'priority tickets', 'seasonal check-ins', 'documentation', 'video guides', 'success manager'],
    related: ['customization-options', 'multi-campus-management', 'parent-mobile-app'],
  },
  {
    slug: 'customization-options',
    title: 'Customization Options',
    metaTitle: 'Custom School ERP Workflows | EduPortal Pakistan',
    metaDescription: 'Adapt reports, fee heads, workflows & permissions to your school processes. Flexible customization within stable EduPortal school management software Pakistan.',
    keywords: 'custom school ERP Pakistan, ERP workflow customization schools',
    icon: 'settings-2',
    heroImage: 'assets/dashboard.png',
    heroAlt: 'EduPortal ERP customization options',
    tagline: 'Tailor fields, reports, and workflows without breaking core stability.',
    pain: 'rigid software that forces your school to change established processes',
    outcomes: 'flexible configuration, custom reports, and role-fit permissions',
    modules: ['custom fee heads', 'report layouts', 'role permissions', 'custom fields', 'workflow rules', 'branded documents', 'API options', 'integration support', ' phased rollout', 'change management'],
    related: ['customer-support', 'multi-campus-management', 'accounting-management'],
  },
];

export const FEATURE_MAP = Object.fromEntries(FEATURES.map((f) => [f.slug, f]));
